f_run_sa <- function(params, wtp) {
  #' Run the model for deterministic sensitivity analysis
  #'
  #' Evaluates the health economic model for a single parameter set and formats
  #' the results as a cost-effectiveness table suitable for deterministic
  #' sensitivity analysis and other post-processing routines.
  #'
  #' The returned data frame contains total costs, QALYs and net monetary
  #' benefit (NMB) for each treatment strategy, together with incremental
  #' cost-effectiveness outcomes.
  #'
  #' @param params Named list (or single row of the data frame returned by
  #'   `f_input()`) containing one complete set of model parameters.
  #' @param wtp Numeric. Willingness-to-pay threshold used to calculate net
  #'   monetary benefit.
  #'
  #' @details
  #' The function evaluates `f_model()` for a single parameter set and
  #' reformats the model outputs into a data frame compatible with
  #' deterministic sensitivity analysis workflows, including
  #' `dampack::run_owsa_det()`.
  #'
  #' For each treatment strategy, the following outcomes are reported:
  #' \itemize{
  #'   \item Total discounted costs.
  #'   \item Total discounted QALYs.
  #'   \item Net monetary benefit (NMB).
  #'   \item Incremental costs.
  #'   \item Incremental QALYs.
  #'   \item Incremental cost-effectiveness ratio (ICER).
  #'   \item Incremental net monetary benefit (INMB).
  #' }
  #'
  #' Net monetary benefit is calculated as:
  #' \deqn{
  #' NMB = (QALYs \times WTP) - Costs
  #' }
  #'
  #' @return A data frame with one row per treatment strategy containing:
  #' \itemize{
  #'   \item `Option`
  #'   \item `Cost`
  #'   \item `QALY`
  #'   \item `NMB`
  #'   \item `iCost`
  #'   \item `iQALY`
  #'   \item `iCER`
  #'   \item `iNMB`
  #' }
  #'
  #' @seealso
  #' `f_model()` for evaluating a single parameter set.
  #'
  #' `f_input()` for generating model input parameters.
  #'
  #' @examples
  #' # Generate deterministic inputs
  #' df_input <- f_input(
  #'   n_sim = 1,
  #'   setting = 1
  #' )
  #'
  #' # Run deterministic cost-effectiveness analysis
  #' f_run_sa(
  #'   params = df_input[1, ],
  #'   wtp = 30000
  #' )
  #'
  #' @export
  
  # Run model simulation
  v_results <- f_model(params)
  
  # Create results dataframe for cost-effectiveness analysis
  df_results <- data.frame(
    Option = v_treatments,
    QALY = c(v_results[3], v_results[4]),
    Cost = c(v_results[1], v_results[2]),
    NMB = c(v_results[3] * wtp - v_results[1], v_results[4] * wtp - v_results[2]),
    iQALY = rep(v_results[4] - v_results[3], n_treatments),
    iCost = rep(v_results[2] - v_results[1], n_treatments),
    iCER = rep((v_results[2] - v_results[1]) / (v_results[4] - v_results[3]), n_treatments),
    iNMB = rep((v_results[4] * wtp - v_results[2]) - (v_results[3] * wtp - v_results[1]), n_treatments)
  )
  
  return(df_results)
}

f_run_intermediate <- function(params) {
  #' Run the model for multiple parameter sets and collect intermediate outputs
  #'
  #' Evaluates the health economic model for multiple parameter sets and stores
  #' the intermediate cycle-level outputs returned by `f_model()` in a
  #' three-dimensional array.
  #'
  #' This function is primarily intended for probabilistic sensitivity analysis
  #' (PSA), model validation and visualization of cycle-level outcomes.
  #'
  #' @param params A data frame containing one complete set of model parameters
  #'   per row, typically generated by `f_input()`.
  #'
  #' @details
  #' The function iterates over all rows in `params`, evaluates
  #' `f_model(intermediate = TRUE)` for each parameter set, and combines the
  #' resulting matrices into a three-dimensional array with dimensions:
  #'
  #' \itemize{
  #'   \item Cycles.
  #'   \item Intermediate model outputs.
  #'   \item Simulations.
  #' }
  #'
  #' Intermediate outputs include cycle-level:
  #' \itemize{
  #'   \item Health-state costs.
  #'   \item Toxicity costs.
  #'   \item Event costs.
  #'   \item Health-state QALYs.
  #'   \item Toxicity disutilities.
  #'   \item Health-state life-years.
  #'   \item Toxicity prevalence.
  #' }
  #'
  #' @return A three-dimensional array with dimensions
  #' `(cycles, outputs, simulations)`, where:
  #' \itemize{
  #'   \item Dimension 1 represents model cycles.
  #'   \item Dimension 2 contains the intermediate outputs returned by
  #'         `f_model(intermediate = TRUE)`.
  #'   \item Dimension 3 represents individual parameter sets (simulations).
  #' }
  #'
  #' @seealso
  #' `f_input()` for generating model input parameters.
  #'
  #' `f_model()` for evaluating a single parameter set.
  #'
  #' @examples
  #' # Generate deterministic inputs
  #' df_input <- f_input(
  #'   n_sim = 10,
  #'   setting = 1
  #' )
  #'
  #' # Run the model for all parameter sets
  #' a_results <- f_run_intermediate(df_input)
  #'
  #' dim(a_results)
  #'
  #' @export
  
  # create array to store results; 3 dimensions (cycles, outcomes, simulations)
  a_results <- array(data = NA, 
                     dim = c(n_t + 1, # number of cycles
                             3 * n_treatments * (length(v_states) + length(v_tox) + 1), # number of results (number of outcomes * number of treatments * number of health states/events/toxicities)
                             dim(params)[1] # number of simulations
                     ), # close dim
                     dimnames = list( # name dimensions
                       paste0("cycle_", 1:(n_t + 1)),
                       c(paste0("Cost_", v_states, "_", v_treatments[1]),   # Cost per health state for t1
                         paste0("Cost_", v_tox, "_", v_treatments[1]),      # Tox cost for t1
                         paste0("Cost_Event_", v_treatments[1]),            # Event cost for t1
                         
                         paste0("Cost_", v_states, "_", v_treatments[2]),   # Cost per health state for t2
                         paste0("Cost_", v_tox, "_", v_treatments[2]),      # Tox cost for t2
                         paste0("Cost_Event_", v_treatments[2]),            # Event cost for t2
                         
                         paste0("QALY_", v_states, "_", v_treatments[1]),   # QALYs per health state for t1
                         paste0("QALY_", v_tox, "_", v_treatments[1]),      # Tox QALY for t1
                         paste0("QALY_Event_", v_treatments[1]),            # Event QALY for t1
                         
                         paste0("QALY_", v_states, "_", v_treatments[2]),   # QALYs per health state for t2
                         paste0("QALY_", v_tox, "_", v_treatments[2]),      # Tox QALY for t2
                         paste0("QALY_Event_", v_treatments[2]),            # Event QALY for t2
                         
                         paste0("LY_", v_states, "_", v_treatments[1]),     # LYs per health state for t1 (Markov trace)
                         paste0("Incidence_", v_tox, "_", v_treatments[1]), # Tox incidence for t1
                         paste0("LY_Event_", v_treatments[1]),              # Event LYs for t1
                         
                         paste0("LY_", v_states, "_", v_treatments[2]),     # LYs per health state for t2 (Markov trace)
                         paste0("Incidence_", v_tox, "_", v_treatments[2]), # Tox incidence for t2
                         paste0("LY_Event_", v_treatments[2])               # Event LYs for t2
                       ), # end c
                       paste0("sim_", 1:dim(params)[1])
                     ) # close dimnames 
  ) # end array 
  
  # Run model simulation
  for (x in 1:dim(params)[1]) a_results[,,x ] <- f_model(params[x, ], intermediate = TRUE)
  
  return(a_results)
}


